name = "workout"
compatibility_date = "2026-06-07"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "workout-profiles"
database_id = "00000000-0000-0000-0000-000000000000"
